apiVersion: noi.ibm.com/v1beta1
kind: NOI
metadata:
  name: evtmanager
  annotations:
    argocd.argoproj.io/sync-wave: "120"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  license:
    accept: true
  advanced:
    antiAffinity: false
    imagePullPolicy: IfNotPresent
    imagePullRepository: cp.icr.io/cp/noi
  ldap:
    mode: standalone
    storageSize: 1Gi
    storageClass: 'ibmc-block-gold'
  backupRestore:
    enableAnalyticsBackups: false
  version: 1.6.7
  entitlementSecret: ibm-entitlement-key
  clusterDomain: cpi4i-classic-fra02-b3c-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
  persistence:
    storageClassMinio: 'ibmc-block-gold'
    storageSizeMinio: 5Gi
    storageSizeNCOBackup: 5Gi
    enabled: true
    storageSizeNCOPrimary: 5Gi
    storageClassNCOPrimary: 'ibmc-block-gold'
    storageSizeImpactServer: 5Gi
    storageClassImpactServer: 'ibmc-block-gold'
    storageClassKafka: 'ibmc-block-gold'
    storageSizeKafka: 50Gi
    storageClassCassandraBackup: 'ibmc-block-gold'
    storageSizeCassandraBackup: 50Gi
    storageClassZookeeper: 'ibmc-block-gold'
    storageClassCouchdb: 'ibmc-block-gold'
    storageSizeZookeeper: 5Gi
    storageSizeCouchdb: 20Gi
    storageClassCassandraData: 'ibmc-block-gold'
    storageSizeCassandraData: 50Gi
    storageClassElastic: 'ibmc-block-gold'
    storageClassImpactGUI: 'ibmc-block-gold'
    storageSizeImpactGUI: 5Gi
    storageSizeElastic: 75Gi
    storageClassNCOBackup: 'ibmc-block-gold'
  deploymentType: trial
  topology:
    storageClassElasticTopology: 'ibmc-block-gold'
    storageSizeElasticTopology: 75Gi
    storageSizeFileObserver: 5Gi
    storageClassFileObserver: 'ibmc-block-gold'
    iafCartridgeRequirementsName: ''
    appDisco:
      enabled: false
    observers:
      docker: true
      taddm: false
      servicenow: false
      ibmcloud: true
      alm: false
      contrail: false
      cienablueplanet: false
      kubernetes: true
      bigfixinventory: false
      junipercso: false
      dns: true
      itnm: false
      ansibleawx: false
      ciscoaci: false
      azure: false
      rancher: false
      newrelic: false
      vmvcenter: true
      rest: true
      appdynamics: true
      jenkins: false
      zabbix: false
      file: true
      googlecloud: false
      dynatrace: false
      aws: false
      openstack: false
      vmwarensx: false
    netDisco: false
